Mentoring t 47
BI-kotlin-in-action/SoyeonPark pull request #1
Opened 2023-10-20 06:16 UTC by soyeom

PR 인지가 늦어서 죄송합니다 ㅠ ㅠ
merge conflict가 있어서 해결 후 올립니다!

**질문**
1. 인터넷을 찾아보면 BufferedReader로 입력 받기를 권장하던데 대부분의 경우 이렇게 입력 받으면 될까요??
2. 두 파일에서 string을 int로 변환하는 방법이 각각 다른데..혹시 어느 방법을 권장하시나요??

2023-10-20 08:59 UTC, konempty commented
<img width="357" alt="스크린샷 2023-10-20 오후 5 59 03" src="https://github.com/BI-kotlin-in-action/SoyeonPark/assets/44064530/efc63318-664c-41f6-9164-d38f8a606670">
저번 강의 시간에 말씀드린것 처럼 리뷰어 등록을 해주셔야 제가 인지할수 있습니다..!
다음부터는 저를 리뷰어로 등록해주세요

2023-10-20 09:11 UTC, konempty requested changes
고생하셨습니다 👍 👍 
조금만더 수정 부탁드릴게요~!

2023-10-20 09:11 UTC, konempty commented on .gitignore
> +.idea
<img width="354" alt="스크린샷 2023-10-20 오후 6 00 28" src="https://github.com/BI-kotlin-in-action/SoyeonPark/assets/44064530/32036c63-85bd-45b7-bcb2-e561250a7859">

파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/2480.kt
> +    val br = BufferedReader(InputStreamReader(System.`in`))
요정도 작은 코드에서는 bufferedReader를 안쓰셔도 좋아요 ㅋㅋㅋㅋ
개취이지만 간편하게 readln()으로 처리하셔도 좋을것 같아요!
그리고 자바에서는 stream을 쓸땐 끝날때 close()를 해주셔야해요 ㅎㅎ

그리고 BufferedReader의 Best practice는 주열님이 잘 사용하셨는데 아래 주열님 코드를 확인해주세요~!
https://github.com/BI-kotlin-in-action/Juyeol-Song/blob/5c3586b2587fbb24115cafd73aca0e91d88a718a/Boj2533.kt#L34

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/2480.kt
> +        listOf(first, second, third).max() * 100
코틀린에서는 maxOf라는 메소드가 있어서 아래와 같이 최적화가 가능합니다~!
```kotlin
maxOf(first, second, third) * 100
```

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/2480.kt
> +    val third = Integer.parseInt(st.nextToken())
toInt를 쓰는게 더 코틀린스러운 코드라서 Integer.parseInt대신에 toInt를 사용해주세요~!

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/2480.kt
> +    println("$total")
이경우 굳이 스트링으로 형변환 할필요 없이
```kotlin
println(total)
```
로 하시는게 좋을것 같아요!

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/25304.kt
> +import java.util.*
헉 와일드 카드 임포트는 지양하는게 좋습니다
https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij
요 블로그 참고해서 설정해주세요!

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/25304.kt
> +    val n = br.readLine().toInt()
요기서 사용한 toInt가 더 좋은 코드일것 같습니다!

2023-10-20 09:11 UTC, konempty commented on src/main/kotlin/25304.kt
> +    for (i in 1..n) {
i는 사용되지 않은 변수일것 같은데
그럴경우 repeat(n)을 통해서 사용하시는게 좋습니다~!

2023-10-20 09:13 UTC, konempty commented on src/main/kotlin/2480.kt
> +    val br = BufferedReader(InputStreamReader(System.`in`))
인풋 아웃풋 성능이 중요할 정도로 대용량을 다루는 알고리즘 문제도 있는데
그럴때 Buffered(Reader/Writer)를 사용하시면 됩니다!

2023-10-20 14:28 UTC, soyeom commented on src/main/kotlin/2480.kt
> +        listOf(first, second, third).max() * 100
오 이거 예제에서 봤던 기억이 납니다! 감사합니다

2023-10-20 15:54 UTC, soyeom commented
> 고생하셨습니다 👍 👍 조금만더 수정 부탁드릴게요~!

2023-10-20 15:56 UTC, soyeom commented
수정했습니다! 지금꺼 merge하고 다시 pr 보내면 될까요?!

2023-10-21 06:32 UTC, konempty commented
<img width="362" alt="스크린샷 2023-10-21 오후 3 31 06" src="https://github.com/BI-kotlin-in-action/SoyeonPark/assets/44064530/38194962-cf5e-4afb-a931-e949446820c9">

PR accept 될때까진 머지 하시면 안되구요
리뷰 받은 내용을 적용 하신 이후에는 요 버튼을 눌러주셔야 저한테 알림이 와서 
추가 리뷰를 드려도 되는지 혹은 아직 리뷰 반영중인지 알수있습니다~!

2023-10-21 06:38 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
더 수정할만한게 눈에 띄긴 하지만 나중에 좀더 심화 내용을 배우고 난뒤에 알려드리겠습니다~!
요번 코멘트 적용 후 머지하시면 됩니다!

2023-10-21 06:38 UTC, konempty commented on src/main/kotlin/week1/25304.kt
> +            total == sum ->
케이스가 두개라면 when보다는 if-else가 더 나을수도 있습니다!
```kotlin
println(if (total == sum) "Yes" else "No")
```

2023-10-23 15:05 UTC, merged